#!/usr/bin/env bash
# _meta/generate-contracts.sh — derives, for each category, the short CONTRACTS index from the
# specs: agents/NN-category/CONTRACTS.md with, per agent, the Phases/Type/Suggested model lines
# from Identification, the Inputs and Outputs tables, the Rules, the Limitations and the Done
# criteria checklist (≈35 % of a spec's bytes — what the briefing needs). This is what the
# Orchestrator reads to build the dependency graph, classify the fan-out by model tier and
# validate deliveries — without loading whole specs into its own context
# (workflows/README.md §What each session reads). The executor (the summoned agent) still reads
# the full spec: the spec is the source, this is a view.
#
# Usage:
#   bash _meta/generate-contracts.sh          regenerates the 15 CONTRACTS.md (commit in the same step)
#   bash _meta/generate-contracts.sh --check  exit 1 if any differs from what the specs give
#                                             (this is check 19 of _meta/verify.sh)
set -uo pipefail
cd "$(dirname "$0")/.."
export LC_ALL=C   # same file order on every machine (check 19 compares byte for byte)

gera() { # $1 = category folder → stdout
  local cat="$1" f nome
  printf '# Derived contracts — `%s`\n\n' "$cat"
  printf '> **Generated by `_meta/generate-contracts.sh` from the specs in this category — do not edit: each spec is the source.**\n'
  printf '> One entry per agent with what the Orchestrator needs in order to summon, route and validate (phases, type,\n'
  printf '> model tier, inputs, outputs, rules, limitations, done criteria). Read the ENTRY for the agent being summoned\n'
  printf '> (`## name`), not the whole file. The summoned agent reads the full spec. Regenerate with\n'
  printf '> `bash _meta/generate-contracts.sh`; check 19 of `_meta/verify.sh` flags drift. Category index: `%s/README.md`.\n\n' "$cat"
  for f in "$cat"/*.md; do
    case "$(basename "$f")" in README.md | CONTRACTS.md | AGENT-TEMPLATE.md) continue ;; esac
    nome=$(basename "$f" .md)
    printf '## %s\n\n' "$nome"
    printf 'Full spec: `%s`\n\n' "$f"
    printf '| Field | Value |\n| --- | --- |\n'
    awk '/^## Identification/{p=1;next} /^## /{p=0} p && /^\| \*\*(Phases|Type|Suggested model)\*\*/' "$f"
    printf '\n### Inputs\n\n'
    awk '/^## Inputs/{p=1;next} /^## /{p=0} p && /^\|/' "$f" | grep . || printf '_(no table — see the spec)_\n'
    printf '\n### Outputs\n\n'
    awk '/^## Outputs/{p=1;next} /^## /{p=0} p && /^\|/' "$f" | grep . || printf '_(no table — see the spec)_\n'
    printf '\n### Rules\n\n'
    awk '/^## Rules/{p=1;next} /^## /{p=0} p && /^[0-9]+\. |^- /' "$f" | grep . || printf '_(see the spec)_\n'
    printf '\n### Limitations\n\n'
    awk '/^## Limitations/{p=1;next} /^## /{p=0} p && /^- /' "$f" | grep . || printf '_(see the spec)_\n'
    printf '\n### Done criteria\n\n'
    awk '/^## Done criteria/{p=1;next} /^## /{p=0} p && /^- \[/' "$f" | grep . || printf '_(no checklist — see the spec)_\n'
    printf '\n'
  done
  printf '## Related\n\n'
  printf -- '- `%s/README.md` — the human index of the category (order of work, who does what).\n' "$cat"
  printf -- '- `agents/README.md` — how the Orchestrator reads a spec (contract vs. script).\n'
  printf -- '- `workflows/README.md` — what each session reads; where this index fits.\n'
  printf -- '- `core/model-routing.md` — the tiers the "Suggested model" column cites.\n'
}

modo="${1:-}"
case "$modo" in '' | --check) ;; *) printf 'Usage: generate-contracts.sh [--check]\n'; exit 1 ;; esac
diverge=0
for cat in agents/[0-9][0-9]-*/; do
  cat="${cat%/}"
  if [ "$modo" = "--check" ]; then
    if [ ! -f "$cat/CONTRACTS.md" ] || ! diff -q <(gera "$cat") "$cat/CONTRACTS.md" >/dev/null 2>&1; then
      printf '✗ %s/CONTRACTS.md out of date or missing\n' "$cat"; diverge=1
    fi
  else
    gera "$cat" > "$cat/CONTRACTS.md"
    printf '✓ %s/CONTRACTS.md\n' "$cat"
  fi
done
[ "$modo" = "--check" ] && [ "$diverge" -eq 0 ] && printf '✓ derived contracts up to date\n'
exit "$diverge"
