#!/usr/bin/env bash
# _meta/verify.sh — the framework's own gate ("Gates, not gut feelings", MANIFESTO.md §7).
# Checks Maestro's internal consistency. Run from the framework root or from anywhere
# (the script repositions itself). Exits with code 1 on failures — serves as a gate in CI
# or in playbooks/add-an-agent.md.
# Line-ending guard: a copy with CRLF (Windows) failed with cryptic errors and the gate never ran.
# The `#` at the end of the next line makes it immune to the very \r it detects.
case "$(head -c 4000 "$0")" in *$'\r'*) printf '✗ %s has CRLF line endings — restore with git checkout (the copy .gitattributes prevents the conversion) or: sed -i "s/\\r$//" %s\n' "$0" "$0"; exit 2 ;; esac #
set -uo pipefail
cd "$(dirname "$0")/.."
# Deterministic locale: under LC_ALL=C, [^[:alnum:]] matches the bytes of accented characters and
# "§Sess" resolved against "## Sessão"; CI runs C.UTF-8 — the gate must give the same answer
# everywhere.
if locale -a 2>/dev/null | grep -qiE '^C\.utf-?8$'; then export LC_ALL=C.UTF-8; fi

# --integrity mode (--integridade also accepted): compares the local copy against the
# release manifest (_meta/SHA256SUMS, generated by the upstream release.yml). Detects
# silent drift from the "the copy is read-only" rule in any session, without waiting
# for the sync.
# Exits 0 (intact), 1 (diverges) or 2 (NOT VERIFIABLE: no checksum tool on PATH — a red
# light about something nobody looked at is as dishonest as a green one).
case "${1:-}" in
  --integrity|--integridade) : ;;
  --*) printf '✗ unknown flag: %s (did you mean --integrity?)\n' "${1}"; exit 1 ;;
  *) ;;
esac
if [ "${1:-}" = "--integrity" ] || [ "${1:-}" = "--integridade" ]; then
  if [ ! -f _meta/SHA256SUMS ]; then
    printf '✗ no _meta/SHA256SUMS manifest (this is a working clone, not a release ZIP)\n'
    exit 1
  fi
  if command -v sha256sum >/dev/null 2>&1; then somas='sha256sum'
  elif command -v shasum >/dev/null 2>&1; then somas='shasum -a 256'
  else
    printf -- '— integrity: NOT VERIFIABLE (no sha256sum or shasum on PATH — install coreutils)\n'
    exit 2
  fi
  # `-c` only looks at what is listed: an EXTRA file inside the copy (a local note, an invented
  # spec) passed as "identical". Extras are drift just as much as edits are.
  extras=$(comm -13 <(awk '{print $2}' _meta/SHA256SUMS | sort) \
                   <(find . -type f ! -path './.git/*' ! -path './_meta/SHA256SUMS' | sed 's|^\./||' | sort))
  if [ -z "$extras" ] && $somas -c --quiet _meta/SHA256SUMS 2>/dev/null; then
    printf '✓ integrity: the copy is identical to the origin release.\n'
    exit 0
  else
    [ -n "$extras" ] && { printf '✗ integrity: file(s) that do not come from the release:\n'; printf '%s\n' "$extras" | head -10; }
    printf '✗ integrity: the copy DIVERGES from the origin release — every difference is a local edit\n'
    printf '  to reconcile (playbooks/sync-framework.md step 3) and, almost always, an entry\n'
    printf '  for the project FRAMEWORK-IMPROVEMENTS.md.\n'
    printf '  If ALL files fail on a Windows machine, it is Git CRLF conversion: restore the copy\n'
    printf '  (git checkout -- Maestro/) with the copy .gitattributes already in the repository.\n'
    $somas -c _meta/SHA256SUMS 2>/dev/null | grep -v ': OK$' | head -20
    exit 1
  fi
fi

# Any other argument is a typo, not a mode: without this guard, `verify.sh --integrit`
# (or `xyz`) fell through to the default sweep and printed "Framework consistent" with exit 0 —
# a gate printing green about a mode that never ran.
if [ -n "${1:-}" ]; then
  printf '✗ unknown argument: %s\n' "$1"
  printf '  Usage: verify.sh [--integrity]\n'
  exit 1
fi

falhas=0
falha() { printf '✗ %s\n' "$*"; falhas=$((falhas + 1)); }
ok() { printf '✓ %s\n' "$*"; }

# A file that is legitimately cited but legitimately absent from a distributed copy:
# it is listed in _meta/DO-NOT-DISTRIBUTE. Absent AND listed is not a break — it is
# the confidentiality lever working. (The integrity manifest is one such case.)
upstream_only() {
  [ "$1" = "_meta/SHA256SUMS" ] && return 0
  [ -f _meta/DO-NOT-DISTRIBUTE ] || return 1
  while IFS= read -r l; do
    case "$l" in '' | \#*) continue ;; esac
    case "$1" in $l) return 0 ;; esac
  done < _meta/DO-NOT-DISTRIBUTE
  return 1
}

# Distributable tree = tracked files + new ones not yet added (honouring .gitignore); without
# git, the disk outside .git. A file created mid-session and not yet `git add`ed is the most
# common case — and it was invisible to check 14 (which only saw `git ls-files`), while check 2
# counted even what .gitignore declares temporary. Both checks now share one notion of
# "what gets distributed".
lista_alvos() {
  if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
    git -c core.quotePath=false ls-files --cached --others --exclude-standard
  fi | grep . || find . -type f -not -path './.git/*' | sed 's|^\./||'
}

# The agent specs (excludes READMEs, the template and the derived CONTRACTS.md)
fichas() { find agents -mindepth 2 -type f -name '*.md' ! -name 'README.md' ! -name 'AGENT-TEMPLATE.md' ! -name 'CONTRACTS.md'; }

# ---------------------------------------------------------------------------
# 1. Inventory → disk: every path listed in _meta/INVENTORY.md exists
# ---------------------------------------------------------------------------
em_falta=0
while IFS= read -r p; do
  [ -e "$p" ] || upstream_only "$p" || { falha "MISSING ON DISK (listed in the inventory): $p"; em_falta=1; }
done < <(grep -oE '^- `[^`]+`' _meta/INVENTORY.md | sed 's/^- `//;s/`$//')
[ "$em_falta" -eq 0 ] && ok "inventory → disk: all paths exist"

# ---------------------------------------------------------------------------
# 2. Disk → inventory: every content file is listed in the inventory
# ---------------------------------------------------------------------------
fora=0
while IFS= read -r f; do
  case "$f" in .github/*) continue ;; esac
  grep -qF "\`$f\`" _meta/INVENTORY.md || { falha "NOT IN THE INVENTORY: $f"; fora=1; }
done < <(lista_alvos | grep -E '\.(md|template)$')
[ "$fora" -eq 0 ] && ok "disk → inventory: no unregistered files"

# ---------------------------------------------------------------------------
# 3. Cross-references: every framework path cited in backticks exists
#    (ignores documented placeholders: NN-categoria, Wnn/Lnn, {{...}}, and the files that
#    only exist in release copies: SHA256SUMS, ORIGIN)
# ---------------------------------------------------------------------------
quebradas=0
while IFS= read -r p; do
  case "$p" in
    *NN-* | *nome-do-agente* | *agent-name* | *Wnn* | *Lnn* | *dimensao* | *dimension* | *AAAA* | *YYYY* | \
    *SHA256SUMS* | *_meta/ORIGIN* | *'{{'*) continue ;;
  esac
  [ -e "$p" ] || upstream_only "$p" || { falha "BROKEN REFERENCE: $p"; quebradas=1; }
done < <(grep -rhoE '`(core|agents|workflows|loops|modules|templates|checklists|playbooks|pipelines|knowledge|adapters|starters|_meta)/[A-Za-z0-9._{}/-]+`' \
  --include='*.md' --include='*.template' . | sed 's/`//g' | sort -u)
[ "$quebradas" -eq 0 ] && ok "cross-references: all resolve"

# ---------------------------------------------------------------------------
# 4. Agent specs: all AGENT-TEMPLATE sections present
# ---------------------------------------------------------------------------
seccoes_pt=(
  '## Identificação' '## Objetivo' '## Quando inicia' '## Quando termina'
  '## Inputs' '## Outputs' '## Perguntas ao utilizador' '## Regras'
  '## Limitações' '## Workflow' '## Exemplos' '## Boas práticas'
  '## Anti-padrões' '## Interações' '## Critérios de pronto'
)
seccoes_en=(
  '## Identification' '## Objective' '## When it starts' '## When it ends'
  '## Inputs' '## Outputs' '## Questions to the user' '## Rules'
  '## Limitations' '## Workflow' '## Examples' '## Best practices'
  '## Anti-patterns' '## Interactions' '## Done criteria'
)
# PT→EN transition: a spec passes if ALL sections of ONE of the sets exist (and in order)
conjunto_da_ficha() { # returns pt|en|nenhum
  if grep -qF '## Identification' "$1"; then echo en; elif grep -qF '## Identificação' "$1"; then echo pt; else echo nenhum; fi
}
fichas_ko=0
while IFS= read -r f; do
  cj=$(conjunto_da_ficha "$f")
  [ "$cj" = nenhum ] && { falha "SPEC WITHOUT RECOGNIZABLE SECTIONS: $f"; fichas_ko=1; continue; }
  if [ "$cj" = en ]; then lista=("${seccoes_en[@]}"); else lista=("${seccoes_pt[@]}"); fi
  for s in "${lista[@]}"; do
    grep -qF "$s" "$f" || { falha "SPEC MISSING SECTION '$s': $f"; fichas_ko=1; }
  done
done < <(fichas)
[ "$fichas_ko" -eq 0 ] && ok "agent specs: all template sections present"

# ---------------------------------------------------------------------------
# 5. Language: no residual Portuguese (common PT words that never belong in EN prose)
#    (the STYLE-GUIDE is exempt: it mentions the forbidden terms as examples)
# ---------------------------------------------------------------------------
if grep -rniE 'usuário|deletar|gerenciar|gerenciamento|banco de dados|\barquivos\b|\bregistros?\b|\bcontatos?\b|cadastr|\bacessar\b|planejam|\bescopos?\b|\bsenhas?\b|conex(ão|ões)|implanta(r|do|da|ção)|\bficheiros?\b|\butilizador(es)?\b|\bportão\b|\bportões\b' \
  --include='*.md' --include='*.template' --exclude='STYLE-GUIDE.md' . | cut -c1-160 | grep . ; then
  falha "Portuguese residue detected in the files above (use user/delete/manage/database/scope/password/connection/deploy/file/gate)"
else
  ok "language: no Portuguese residue detected"
fi

# ---------------------------------------------------------------------------
# 6. Artifact graph: product/… paths only inside the canonical tree
#    (core/artifact-protocol.md) and no non-canonical aliases — at the 1st level
#    (phase folder) and at the 2nd level (subfolder), because a mandatory input with the
#    wrong name is a graph edge that never resolves.
#    (_meta/VERSION.md exempt: the changelog describes the old names as history.)
# ---------------------------------------------------------------------------
grafo_ko=0
while IFS= read -r p; do
  case "$p" in
    product | product/ | product/00-discovery* | product/01-requirements* | product/02-architecture* | \
    product/03-experience* | product/04-specification* | product/05-security* | product/06-tests* | \
    product/07-operations* | product/08-documentation* | product/99-records*) ;;
    *) falha "FOLDER OUTSIDE THE CANONICAL TREE (core/artifact-protocol.md): $p"; grafo_ko=1 ;;
  esac
done < <(grep -rhoE '`product/[A-Za-z0-9._/-]*' --include='*.md' --include='*.template' --exclude='VERSION.md' . | sed 's/^`//' | sort -u)
# 2nd level: only the subfolders the protocol tree declares
while IFS= read -r p; do
  case "$p" in
    00-discovery/personas | 00-discovery/use-cases | \
    02-architecture/proposals | 02-architecture/decisions | \
    03-experience/wireframes | \
    04-specification/modules | 04-specification/api | 04-specification/backend | 04-specification/frontend | \
    05-security/sbom | \
    06-tests/test-plans | \
    07-operations/runbooks | 07-operations/secrets | 07-operations/flags | 07-operations/data | \
    07-operations/infra | 07-operations/proxy | 07-operations/cdn | 07-operations/edge | \
    07-operations/load-balancing | 07-operations/deploy | \
    99-records/reviews | 99-records/audits | 99-records/guardians | 99-records/evolutions | \
    99-records/incidents | 99-records/gates | 99-records/quality | \
    99-records/data | 99-records/backups | 99-records/security | 99-records/ha) ;;
    *) falha "SUBFOLDER OUTSIDE THE CANONICAL TREE (core/artifact-protocol.md): product/$p/"; grafo_ko=1 ;;
  esac
done < <(grep -rhoE '`product/[0-9]{2}-[a-z-]+/[a-z-]+/' --include='*.md' --include='*.template' --exclude='VERSION.md' . | sed 's/^`product\///; s/\/$//' | sort -u)
# prefixed aliases (old or invented names for canonical artifacts)
if grep -rnE 'product/01-requirements/(requirements\.md|non-functional-requirements\.md)|product/00-discovery/(priorities|use-cases|kpis)\.md|product/02-architecture/(adr|style\.md|infra\.md)|product/04-specification/business-rules\.md|product/07-operations/data/disaster-recovery\.md' \
  --include='*.md' --include='*.template' --exclude='VERSION.md' . ; then
  falha "NON-CANONICAL artifact ALIAS (canonical: functional-requirements.md, nfr.md, prioritization.md, use-cases/, goals-and-kpis.md, decisions/, architecture-vision.md, 01-requirements/business-rules.md, dr-plan.md)"
  grafo_ko=1
fi
# aliases WITHOUT the prefix in the process folders (a workflow tells the agent the file to create)
if grep -rnE '`(priorities|non-functional-requirements)\.md`' --include='*.md' workflows checklists loops playbooks core ; then
  falha "NON-CANONICAL ALIAS without the product/ prefix (use prioritization.md / nfr.md)"
  grafo_ko=1
fi
[ "$grafo_ko" -eq 0 ] && ok "artifact graph: all product/ paths inside the canonical tree"

# ---------------------------------------------------------------------------
# 7. Agent specs: the 15 sections in the template ORDER (check 4 only saw presence)
# ---------------------------------------------------------------------------
ordem_ko=0
while IFS= read -r f; do
  cj=$(conjunto_da_ficha "$f")
  if [ "$cj" = en ]; then lista=("${seccoes_en[@]}"); else lista=("${seccoes_pt[@]}"); fi
  prev=0
  for s in "${lista[@]}"; do
    ln=$(grep -nF "$s" "$f" | head -1 | cut -d: -f1)
    if [ -n "$ln" ]; then
      if [ "$ln" -lt "$prev" ]; then falha "SECTIONS OUT OF ORDER: $f ('$s')"; ordem_ko=1; break; fi
      prev=$ln
    fi
  done
done < <(fichas)
[ "$ordem_ko" -eq 0 ] && ok "agent specs: sections in template order"

# ---------------------------------------------------------------------------
# 8. § anchors: every `file` §Section reference points to an existing heading.
#    Tolerant of trailing prose (shortens the anchor word by word), but the match is
#    ANCHORED at the START of the heading (optional numbering stripped) — the previous
#    version degraded into "the first word is a substring of any heading" and approved
#    §Gate P99 against "Anatomy of a gate". Section labels (§A, §3) must be a heading's
#    label; item IDs (A1, C4, FR-12, AR-7) only need to exist as a token.
#    Second pass: anchors to the project's LIVE files (STATE.md, CLAUDE.md,
#    FRAMEWORK-IMPROVEMENTS.md) resolve against the headings of the matching template —
#    it was the absence of this gate that let 23 citations of a non-existent §Debt through.
# ---------------------------------------------------------------------------
titulos_de() { grep -E '^#{1,6} ' "$1" | sed -E 's/^#+ +//; s/\*\*//g; s/^([0-9]+(\.[0-9]+)*[.)]?|[A-Z][.)]) +([—–-] +)?//'; }
# Strict mode (live files: few headings, and short): the anchor must START with a complete
# heading — "per-block consumption record" does not resolve against "Record history" just by
# sharing the first word; "Done (Cost of AI field" resolves because it starts with "Done".
resolve_estrito() { # $1 = target  $2 = anchor
  local t esc
  while IFS= read -r t; do
    [ -n "$t" ] || continue
    t=$(printf '%s' "$t" | sed -E 's/ *\(.*$//; s/ *[—–-] .*$//; s/ *$//')
    esc=$(printf '%s' "$t" | sed 's/[][\\.*^$(){}+?|]/\\&/g')
    printf '%s' "$2" | grep -qiE "^${esc}([^[:alnum:]]|$)" && return 0
  done < <(titulos_de "$1")
  return 1
}
resolve_ancora() { # $1 = target file  $2 = anchor (without §)  $3 = optional 'estrito' → 0 if it resolves
  local alvo="$1" s="$2" esc prim titulos
  [ "${3:-}" = estrito ] && { resolve_estrito "$alvo" "$s"; return $?; }
  titulos=$(titulos_de "$alvo")
  while [ -n "$s" ]; do
    esc=$(printf '%s' "$s" | sed 's/[][\\.*^$(){}+?|]/\\&/g')
    printf '%s\n' "$titulos" | grep -qiE "^${esc}([^[:alnum:]]|$)" && return 0
    if printf '%s' "$s" | grep -qE '^([A-Z]|[0-9]+)$' && grep -qE "^#{1,6} +${s}[.)] " "$alvo"; then return 0; fi
    local novo="${s% *}"; [ "$novo" = "$s" ] && break; s="$novo"
  done
  prim=${2%% *}
  if printf '%s' "$prim" | grep -qE '^[A-Za-z]{1,3}-?[0-9]+$' && grep -qE "(^|[^A-Za-z0-9])${prim}([^A-Za-z0-9]|$)" "$alvo"; then return 0; fi
  return 1
}
# "§A / §B" and "§AR-2/§AR-18" are several anchors in one: after the first, only the parts
# starting with § count (in "§Lessons / post-mortems", "post-mortems" is prose)
resolve_composta() { # $1 = target  $2 = anchor(s)  $3 = optional 'estrito'  → 0 if all resolve
  local primeira=1 uma
  while IFS= read -r uma; do
    uma=$(printf '%s' "$uma" | sed 's/^ *//; s/ *$//')
    if [ "$primeira" -eq 1 ]; then primeira=0; else case "$uma" in §*) ;; *) continue ;; esac; fi
    uma=${uma#§}
    [ -n "$uma" ] || continue
    case "$uma" in [0-9]* | rule* | Rule* | regra* | Regra*) continue ;; esac   # §N/§rule N refer to numbered list items, not headings
    resolve_ancora "$1" "$uma" "${3:-}" || return 1
  done < <(printf '%s\n' "$2" | tr '/' '\n')
  return 0
}
anc_ko=0
while IFS='|' read -r alvo sec; do
  [ -e "$alvo" ] || continue
  case "$alvo:$sec" in knowledge/ai-pitfalls.md:[0-9]*) falha "PITFALL CITED BY NUMBER: \`$alvo\` §$sec — use §AR-n (stable IDs)"; anc_ko=1; continue ;; esac
  resolve_composta "$alvo" "$sec" || { falha "ORPHAN ANCHOR: \`$alvo\` §$sec"; anc_ko=1; }
done < <(grep -rhoE '`(core|agents|workflows|loops|modules|templates|checklists|playbooks|pipelines|knowledge|adapters|starters|_meta)/[A-Za-z0-9._/-]+` §[A-Za-z0-9][^`,;:)]*' \
  --include='*.md' --include='*.template' . | sed 's/^`//; s/` §/|/; s/\. .*$//; s: · .*$::; s/[ .]*$//' | sort -u)
while IFS='|' read -r vivo sec; do
  tpl="templates/project/${vivo}.template"
  [ -f "$tpl" ] || continue
  resolve_composta "$tpl" "$sec" estrito || { falha "ORPHAN ANCHOR to a live file: \`$vivo\` §$sec (headings in $tpl)"; anc_ko=1; }
done < <(grep -rhoE '`(STATE|CLAUDE|FRAMEWORK-IMPROVEMENTS)\.md` *§[^` ,;:)|][^`,;:)|]*' \
  --include='*.md' --include='*.template' --exclude='VERSION.md' . | sed 's/^`//; s/` *§/|/; s/\. .*$//; s: · .*$::; s/ \+[-—→].*$//; s/[ .]*$//' | sort -u)
[ "$anc_ko" -eq 0 ] && ok "§ anchors: all point to existing headings"

# ---------------------------------------------------------------------------
# 9. References to the root files (MANIFESTO, START-HERE, README) resolve
# ---------------------------------------------------------------------------
raiz_ko=0
while IFS= read -r p; do
  [ -e "$p" ] || { falha "BROKEN REFERENCE (root): $p"; raiz_ko=1; }
done < <(grep -rhoE '`(MANIFESTO\.md|START-HERE\.md|README\.md)`' --include='*.md' --include='*.template' . | sed 's/`//g' | sort -u)
[ "$raiz_ko" -eq 0 ] && ok "root references: resolve"

# ---------------------------------------------------------------------------
# 10. Category indexes: every spec is cited in its category README
# ---------------------------------------------------------------------------
idx_ko=0
while IFS= read -r f; do
  cat=$(dirname "$f")
  [ -f "$cat/README.md" ] || continue
  grep -qF "$(basename "$f")" "$cat/README.md" || { falha "SPEC MISSING FROM THE CATEGORY INDEX: $f"; idx_ko=1; }
done < <(fichas)
[ "$idx_ko" -eq 0 ] && ok "category indexes: all specs indexed"

# ---------------------------------------------------------------------------
# 11. Canonical reference format: no internal markdown links, no category paths
#     missing the top-level folder prefix (STYLE-GUIDE §7)
# ---------------------------------------------------------------------------
if grep -rnE '\]\([A-Za-z0-9_./-]+\)' --include='*.md' --include='*.template' --exclude='README.md' --exclude='CONTRIBUTING.md' . | grep -v '](http' | grep -v '](#' ; then
  falha "internal MARKDOWN LINK (the convention is a backticked path)"
else
  ok "no internal markdown links"
fi
if grep -rnE '`[0-9]{2}-[a-z][a-z-]*/[A-Za-z0-9._-]+`' --include='*.md' --include='*.template' . ; then
  falha "PATH WITHOUT the top-level folder PREFIX (e.g. use agents/NN-category/…)"
else
  ok "paths always carry the top-level prefix"
fi

# ---------------------------------------------------------------------------
# 12. Playbooks: mandatory skeleton (playbooks/README.md)
# ---------------------------------------------------------------------------
pb_ko=0
while IFS= read -r f; do
  for s in '## Preconditions' '## Steps' '## Rollback' '## Related'; do
    grep -qF "$s" "$f" || { falha "PLAYBOOK MISSING SECTION '$s': $f"; pb_ko=1; }
  done
done < <(find playbooks -type f -name '*.md' ! -name 'README.md')
[ "$pb_ko" -eq 0 ] && ok "playbooks: mandatory skeleton present"

# ---------------------------------------------------------------------------
# 13. Live prose counts = disk (the changelog history is left untouched)
# ---------------------------------------------------------------------------
decl=$(grep -oE '[0-9]+ (especialistas|specialists)' README.md | grep -oE '[0-9]+' | head -1)
real=$(fichas | wc -l | tr -d ' ')
if [ -n "$decl" ] && [ "$decl" != "$real" ]; then
  falha "COUNT OUT OF SYNC: README.md declares $decl specialists, the disk has $real"
else
  ok "counts: README ($decl) = disk ($real)"
fi

# ---------------------------------------------------------------------------
# 14. Forbidden-terms sweep: no real name travels inside the copies.
#     Provenance travels by project CODENAME (knowledge/candidates.md §Entry and
#     exit rules, rule 5) — client names, product names and stacks never do.
#     Case-insensitive (one entry catches every capitalization — the case-sensitive version
#     let 15 occurrences of one term travel), sweeps file NAMES too, and never prints the
#     term itself (only its line number in the list): CI logs get distributed as well.
#     The list ships empty on purpose: add your own terms, and list the populated
#     file in _meta/DO-NOT-DISTRIBUTE so the list itself does not travel either.
# ---------------------------------------------------------------------------
if [ ! -f _meta/FORBIDDEN-TERMS ]; then
  printf -- '— forbidden-terms sweep: NOT APPLICABLE (no _meta/FORBIDDEN-TERMS)\n'
else
  alvos=$(lista_alvos | grep -v '^_meta/FORBIDDEN-TERMS$')
  ter_ko=0; i=0; n_termos=0
  while IFS= read -r termo; do
    i=$((i + 1))
    case "$termo" in '' | \#*) continue ;; esac
    n_termos=$((n_termos + 1))
    # -H: with a single file grep omitted the name and the cut printed the content (the term);
    # -e: a term starting with "-" is not an option. The file name is printed only down to its
    # folder when the name itself contains the term.
    while IFS= read -r hit; do
      [ -n "$hit" ] || continue
      f=${hit%%:*}; ln=${hit#*:}
      if printf '%s' "$(basename "$f")" | grep -qiE -e "$termo"; then hit="$(dirname "$f")/[name-with-term]:$ln"; fi
      falha "FORBIDDEN TERM (term no. $i in the list) in $hit"
      ter_ko=1
    done < <(printf '%s\n' "$alvos" | tr '\n' '\0' | xargs -0 grep -niHE -e "$termo" 2>/dev/null | cut -d: -f1,2)
    while IFS= read -r nome; do
      [ -n "$nome" ] || continue
      falha "FORBIDDEN TERM (term no. $i in the list) in the NAME of a file under $(dirname "$nome")/"
      ter_ko=1
    done < <(printf '%s\n' "$alvos" | grep -iE -e "$termo")
  done < _meta/FORBIDDEN-TERMS
  if [ "$n_termos" -eq 0 ]; then
    printf -- '— forbidden-terms sweep: no terms configured (see _meta/FORBIDDEN-TERMS)\n'
  elif [ "$ter_ko" -eq 0 ]; then
    ok "forbidden-terms sweep: no real name in what gets distributed"
  fi
fi

# ---------------------------------------------------------------------------
# 15. Internal § citations in templates: by NAME, never by number.
#     A `§8` pointing inside its own file breaks silently the day a section is
#     inserted — that is how 1.0.3 started sending old sessions into the
#     technical-debt section. `§Name` is immune to renumbering.
#     (A `§N` attached to a backticked path is an external reference to another
#     file's numbered item — legitimate, and governed by check 8.)
# ---------------------------------------------------------------------------
sec_ko=0
while IFS= read -r f; do
  while IFS=: read -r n texto; do
    printf '%s' "$texto" | grep -qE '`[^`]+\.md` *§[0-9]' && continue
    falha "SELF-REFERENTIAL §N CITATION: $f:$n — use §Section name (immune to renumbering)"
    sec_ko=1
  done < <(grep -nE '§[0-9]' "$f")
done < <(find templates -type f -name '*.template' | sort)
[ "$sec_ko" -eq 0 ] && ok "§ citations in templates: by name, not by number"

# ---------------------------------------------------------------------------
# 16–18. Mandatory skeletons for loops, modules and workflows — declared in the folder
#     READMEs since 1.0 and never verified. A loop without an anti-infinite safeguard is
#     the one addition that can set an agent iterating without a ceiling; a workflow
#     without "Decision points" loses the mandatory human approval. Same mechanics as check 12.
# ---------------------------------------------------------------------------
lp_ko=0
while IFS= read -r f; do
  prev=0
  for s in '## Identification' '## Progress metric' '## Entry condition' '## Action' '## Exit condition' '## Anti-infinite-loop safeguard' '## STATE.md record' '## Related'; do
    ln=$(grep -nF "$s" "$f" | head -1 | cut -d: -f1)
    [ -n "$ln" ] || { falha "LOOP MISSING SECTION '$s': $f (loops/README.md — the safeguard is mandatory)"; lp_ko=1; continue; }
    [ "$ln" -ge "$prev" ] || { falha "LOOP WITH SECTIONS OUT OF ORDER: $f ('$s')"; lp_ko=1; }
    prev=$ln
  done
done < <(find loops -type f -name 'L*.md')
[ "$lp_ko" -eq 0 ] && ok "loops: mandatory skeleton present (with anti-infinite safeguard)"

md_ko=0
while IFS= read -r f; do
  for s in '## The problem it solves' '## The model' '## Non-negotiable rules' '## How to adopt it in a new product' '## Variations and trade-offs' '## Example' '## Known pitfalls' '## Related'; do
    grep -qF "$s" "$f" || { falha "MODULE MISSING SECTION '$s': $f (modules/README.md §Common skeleton)"; md_ko=1; }
  done
done < <(find modules -type f -name '*.md' ! -name 'README.md')
[ "$md_ko" -eq 0 ] && ok "modules: mandatory skeleton present"

wf_ko=0
while IFS= read -r f; do
  for s in '## Objective' '## Steps' '## Decision points' '## Loops it opens' '## Related'; do
    grep -qF "$s" "$f" || { falha "WORKFLOW MISSING SECTION '$s': $f (workflows/README.md §Structure)"; wf_ko=1; }
  done
  grep -qiE '^## .*preconditions' "$f" || { falha "WORKFLOW WITHOUT PRECONDITIONS: $f"; wf_ko=1; }
  grep -qiE '^## (Exit gate|Closing condition)' "$f" || { falha "WORKFLOW WITHOUT AN EXIT GATE/CLOSING CONDITION: $f"; wf_ko=1; }
done < <(find workflows -type f -name 'W*.md')
[ "$wf_ko" -eq 0 ] && ok "workflows: common anatomy present (steps, decisions, loops, gate)"

# ---------------------------------------------------------------------------
# 19. Derived contracts: agents/NN-category/CONTRACTS.md = a fresh extraction from the specs
#     (the short index the Orchestrator reads instead of loading whole specs)
# ---------------------------------------------------------------------------
if [ -f _meta/generate-contracts.sh ]; then
  if bash _meta/generate-contracts.sh --check >/dev/null 2>&1; then
    ok "derived contracts: CONTRACTS.md up to date with the specs"
  else
    falha "CONTRACTS OUT OF DATE: run bash _meta/generate-contracts.sh and commit (bash _meta/generate-contracts.sh --check lists the categories)"
  fi
else
  printf -- '— derived contracts: NOT APPLICABLE (no _meta/generate-contracts.sh)\n'
fi

# ---------------------------------------------------------------------------
printf '\n'
if [ "$falhas" -gt 0 ]; then
  printf '✗ Verification FAILED: %d problem(s).\n' "$falhas"
  exit 1
fi
printf '✓ Framework consistent.\n'
