#!/usr/bin/env bash
# _meta/verify.sh — the framework's own gate ("Gates, not gut feelings", MANIFESTO.md §7).
# Checks Maestro's internal consistency. Run from the framework root or from anywhere
# (the script repositions itself). Exits with code 1 on failures — serves as a gate in CI
# or in playbooks/add-an-agent.md.
set -uo pipefail
cd "$(dirname "$0")/.."

# --integridade mode: compares the local copy against the release manifest
# (_meta/SHA256SUMS, generated by the upstream release.yml). Detects silent drift
# from the "the copy is read-only" rule in any session, without waiting for the sync.
if [ "${1:-}" = "--integridade" ]; then
  if [ ! -f _meta/SHA256SUMS ]; then
    printf '✗ no _meta/SHA256SUMS manifest (upstream clone, or copy of a release before 2.5.0)\n'
    exit 1
  fi
  if sha256sum -c --quiet _meta/SHA256SUMS 2>/dev/null; then
    printf '✓ integrity: the copy is identical to the origin release.\n'
    exit 0
  else
    printf '✗ integrity: the copy DIVERGES from the origin release — every difference is a local edit\n'
    printf '  to reconcile (playbooks/sync-framework.md step 2) and, almost always, an entry\n'
    printf '  for the project FRAMEWORK-IMPROVEMENTS.md.\n'
    sha256sum -c _meta/SHA256SUMS 2>/dev/null | grep -v ': OK$' | head -20
    exit 1
  fi
fi

falhas=0
falha() { printf '✗ %s\n' "$*"; falhas=$((falhas + 1)); }
ok() { printf '✓ %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. Inventory → disk: every path listed in _meta/INVENTORY.md exists
# ---------------------------------------------------------------------------
em_falta=0
while IFS= read -r p; do
  [ -e "$p" ] || { falha "MISSING ON DISK (listed in the inventory): $p"; em_falta=1; }
done < <(grep -oE '^- `[^`]+`' _meta/INVENTORY.md | sed 's/^- `//;s/`$//')
[ "$em_falta" -eq 0 ] && ok "inventory → disk: all paths exist"

# ---------------------------------------------------------------------------
# 2. Disk → inventory: every content file is listed in the inventory
# ---------------------------------------------------------------------------
fora=0
while IFS= read -r f; do
  grep -qF "\`$f\`" _meta/INVENTORY.md || { falha "NOT IN THE INVENTORY: $f"; fora=1; }
done < <(find . -type f \( -name '*.md' -o -name '*.template' \) ! -path './.git/*' ! -path './.github/*' | sed 's|^\./||')
[ "$fora" -eq 0 ] && ok "disk → inventory: no unregistered files"

# ---------------------------------------------------------------------------
# 3. Cross-references: every framework path cited in backticks exists
#    (ignores documented placeholders: NN-categoria, Wnn/Lnn, {{...}}, etc.)
# ---------------------------------------------------------------------------
quebradas=0
while IFS= read -r p; do
  case "$p" in
    *NN-* | *nome-do-agente* | *Wnn* | *Lnn* | *dimensao* | *AAAA* | *SHA256SUMS* | *'{{'*) continue ;;
  esac
  [ -e "$p" ] || { falha "BROKEN REFERENCE: $p"; quebradas=1; }
done < <(grep -rhoE '`(core|agents|workflows|loops|modules|templates|checklists|playbooks|pipelines|knowledge|adapters|starters|_meta)/[A-Za-z0-9._{}/-]+`' \
  --include='*.md' --include='*.template' . | sed 's/`//g' | sort -u)
[ "$quebradas" -eq 0 ] && ok "cross-references: all resolve"

# ---------------------------------------------------------------------------
# 4. Agent specs: all AGENT-TEMPLATE sections present
#    (excludes READMEs and the template itself)
# ---------------------------------------------------------------------------
seccoes_pt=(
  '## Identificação' '## Objetivo' '## Quando inicia' '## Quando termina'
  '## Inputs' '## Outputs' '## Perguntas ao utilizador' '## Regras'
  '## Limitações' '## Workflow' '## Exemplos' '## Boas práticas'
  '## Anti-padrões' '## Interações' '## Critérios de pronto'
)
seccoes_en=(
  '## Identification' '## Objective' '## When it starts' '## When it ends'
  '## Inputs' '## Outputs' '## Questions to the user' '## Rules'
  '## Limitations' '## Workflow' '## Examples' '## Best practices'
  '## Anti-patterns' '## Interactions' '## Done criteria'
)
# PT→EN transition: a spec passes if ALL sections of ONE of the sets exist (and in order)
conjunto_da_ficha() { # returns pt|en|nenhum
  if grep -qF '## Identification' "$1"; then echo en; elif grep -qF '## Identificação' "$1"; then echo pt; else echo nenhum; fi
}
fichas_ko=0
while IFS= read -r f; do
  cj=$(conjunto_da_ficha "$f")
  [ "$cj" = nenhum ] && { falha "SPEC WITHOUT RECOGNIZABLE SECTIONS: $f"; fichas_ko=1; continue; }
  if [ "$cj" = en ]; then lista=("${seccoes_en[@]}"); else lista=("${seccoes_pt[@]}"); fi
  for s in "${lista[@]}"; do
    grep -qF "$s" "$f" || { falha "SPEC MISSING SECTION '$s': $f"; fichas_ko=1; }
  done
done < <(find agents -mindepth 2 -type f -name '*.md' ! -name 'README.md' ! -name 'AGENT-TEMPLATE.md')
[ "$fichas_ko" -eq 0 ] && ok "agent specs: all template sections present"

# ---------------------------------------------------------------------------
# 5. Language: PT-PT (detection of the most common Brazilianisms)
#    (the STYLE-GUIDE is exempt: it mentions the forbidden terms as examples)
# ---------------------------------------------------------------------------
if grep -rliE 'usuário|deletar|gerenciar|gerenciamento|banco de dados|\barquivos\b|\bregistros?\b|\bcontatos?\b|cadastr|\bacessar\b|planejam|algalgures' \
  --include='*.md' --include='*.template' --exclude='STYLE-GUIDE.md' . ; then
  falha "PT-BR detected in the files above (use utilizador/apagar/gerir/base de dados)"
else
  ok "language: no Brazilianisms detected"
fi

# ---------------------------------------------------------------------------
# 6. Artifact graph: product/… paths only inside the canonical tree
#    (core/artifact-protocol.md) and no non-canonical aliases.
#    (_meta/VERSION.md exempt: the changelog describes the old names as history.)
# ---------------------------------------------------------------------------
grafo_ko=0
while IFS= read -r p; do
  case "$p" in
    product | product/ | product/00-discovery* | product/01-requirements* | product/02-architecture* | \
    product/03-experience* | product/04-specification* | product/05-security* | product/06-tests* | \
    product/07-operations* | product/08-documentation* | product/99-records*) ;;
    *) falha "FOLDER OUTSIDE THE CANONICAL TREE (core/artifact-protocol.md): $p"; grafo_ko=1 ;;
  esac
done < <(grep -rhoE '`product/[A-Za-z0-9._/-]*' --include='*.md' --include='*.template' --exclude='VERSION.md' . | sed 's/^`//' | sort -u)
if grep -rnE 'product/01-requirements/(requirements\.md|non-functional-requirements\.md)|product/00-discovery/priorities\.md|product/02-architecture/adr' \
  --include='*.md' --include='*.template' --exclude='VERSION.md' . ; then
  falha "NON-CANONICAL artifact ALIAS (canonical names: functional-requirements.md, nfr.md, prioritization.md, decisions/)"
  grafo_ko=1
fi
[ "$grafo_ko" -eq 0 ] && ok "artifact graph: all product/ paths inside the canonical tree"

# ---------------------------------------------------------------------------
# 7. Agent specs: the 15 sections in the template ORDER (check 4 only saw presence)
# ---------------------------------------------------------------------------
ordem_ko=0
while IFS= read -r f; do
  cj=$(conjunto_da_ficha "$f")
  if [ "$cj" = en ]; then lista=("${seccoes_en[@]}"); else lista=("${seccoes_pt[@]}"); fi
  prev=0
  for s in "${lista[@]}"; do
    ln=$(grep -nF "$s" "$f" | head -1 | cut -d: -f1)
    if [ -n "$ln" ]; then
      if [ "$ln" -lt "$prev" ]; then falha "SECTIONS OUT OF ORDER: $f ('$s')"; ordem_ko=1; break; fi
      prev=$ln
    fi
  done
done < <(find agents -mindepth 2 -type f -name '*.md' ! -name 'README.md' ! -name 'AGENT-TEMPLATE.md')
[ "$ordem_ko" -eq 0 ] && ok "agent specs: sections in template order"

# ---------------------------------------------------------------------------
# 8. § anchors: every `file` §Section reference points to an existing heading
#    (tolerant of trailing prose: shortens the anchor word by word before flagging)
# ---------------------------------------------------------------------------
anc_ko=0
while IFS='|' read -r alvo sec; do
  [ -e "$alvo" ] || continue
  case "$sec" in [0-9]* | regra* | Regra*) continue ;; esac   # §N/§rule N refer to numbered list items, not headings
  s="$sec"; achou=0
  while [ -n "$s" ]; do
    if grep -E '^#{1,6} ' "$alvo" | grep -qiF "$s"; then achou=1; break; fi
    novo="${s% *}"; [ "$novo" = "$s" ] && break; s="$novo"
  done
  # Item IDs (A1, C4, FR-12, …) are not headings: they only need to exist as a token in the target
  if [ "$achou" -eq 0 ]; then
    prim=${sec%% *}
    prim1=$(printf '%s' "$prim" | grep -oE '^[A-Za-z]{1,3}-?[0-9]+' || true)
    if printf '%s' "$prim" | grep -qE '^[A-Za-z]{1,3}-?[0-9]+([–-][A-Za-z]{0,3}-?[0-9]+)?$' && [ -n "$prim1" ] && grep -qE "(^|[^A-Za-z0-9])${prim1}([^A-Za-z0-9]|$)" "$alvo"; then
      achou=1
    fi
  fi
  [ "$achou" -eq 1 ] || { falha "ORPHAN ANCHOR: \`$alvo\` §$sec"; anc_ko=1; }
done < <(grep -rhoE '`(core|agents|workflows|loops|modules|templates|checklists|playbooks|pipelines|knowledge|adapters|starters|_meta)/[A-Za-z0-9._/-]+` §[A-Za-z0-9][^`,;:)]*' \
  --include='*.md' --include='*.template' . | sed 's/^`//; s/` §/|/; s/\. .*$//; s: · .*$::; s/[ .]*$//' | sort -u)
[ "$anc_ko" -eq 0 ] && ok "§ anchors: all point to existing headings"

# ---------------------------------------------------------------------------
# 9. References to the root files (MANIFESTO, COMECAR-AQUI, README) resolve
# ---------------------------------------------------------------------------
raiz_ko=0
while IFS= read -r p; do
  [ -e "$p" ] || { falha "BROKEN REFERENCE (root): $p"; raiz_ko=1; }
done < <(grep -rhoE '`(MANIFESTO\.md|COMECAR-AQUI\.md|README\.md)`' --include='*.md' --include='*.template' . | sed 's/`//g' | sort -u)
[ "$raiz_ko" -eq 0 ] && ok "root references: resolve"

# ---------------------------------------------------------------------------
# 10. Category indexes: every spec is cited in its category README
# ---------------------------------------------------------------------------
idx_ko=0
while IFS= read -r f; do
  cat=$(dirname "$f")
  [ -f "$cat/README.md" ] || continue
  grep -qF "$(basename "$f")" "$cat/README.md" || { falha "SPEC MISSING FROM THE CATEGORY INDEX: $f"; idx_ko=1; }
done < <(find agents -mindepth 2 -type f -name '*.md' ! -name 'README.md' ! -name 'AGENT-TEMPLATE.md')
[ "$idx_ko" -eq 0 ] && ok "category indexes: all specs indexed"

# ---------------------------------------------------------------------------
# 11. Canonical reference format: no internal markdown links, no category paths
#     missing the top-level folder prefix (STYLE-GUIDE §7)
# ---------------------------------------------------------------------------
if grep -rnE '\]\([A-Za-z0-9_./-]+\)' --include='*.md' --include='*.template' --exclude='README.md' --exclude='CONTRIBUTING.md' . | grep -v '](http' | grep -v '](#' ; then
  falha "internal MARKDOWN LINK (the convention is a backticked path)"
else
  ok "no internal markdown links"
fi
if grep -rnE '`[0-9]{2}-[a-z][a-z-]*/[A-Za-z0-9._-]+`' --include='*.md' --include='*.template' . ; then
  falha "PATH WITHOUT the top-level folder PREFIX (e.g. use agents/NN-categoria/…)"
else
  ok "paths always carry the top-level prefix"
fi

# ---------------------------------------------------------------------------
# 12. Playbooks: mandatory skeleton (playbooks/README.md)
# ---------------------------------------------------------------------------
pb_ko=0
while IFS= read -r f; do
  for s in '## Preconditions' '## Steps' '## Rollback' '## Related'; do
    grep -qF "$s" "$f" || { falha "PLAYBOOK MISSING SECTION '$s': $f"; pb_ko=1; }
  done
done < <(find playbooks -type f -name '*.md' ! -name 'README.md')
[ "$pb_ko" -eq 0 ] && ok "playbooks: mandatory skeleton present"

# ---------------------------------------------------------------------------
# 13. Live prose counts = disk (the changelog history is left untouched)
# ---------------------------------------------------------------------------
decl=$(grep -oE '[0-9]+ (especialistas|specialists)' README.md | grep -oE '[0-9]+' | head -1)
real=$(find agents -mindepth 2 -type f -name '*.md' ! -name 'README.md' ! -name 'AGENT-TEMPLATE.md' | wc -l)
if [ -n "$decl" ] && [ "$decl" != "$real" ]; then
  falha "COUNT OUT OF SYNC: README.md declares $decl specialists, the disk has $real"
else
  ok "counts: README ($decl) = disk ($real)"
fi

# ---------------------------------------------------------------------------
printf '\n'
if [ "$falhas" -gt 0 ]; then
  printf '✗ Verification FAILED: %d problem(s).\n' "$falhas"
  exit 1
fi
printf '✓ Framework consistent.\n'
